#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBE793007AD22DF7E (tsujan2000@gmail.com)
#
Name     : lxqt-config
Version  : 1.0.0
Release  : 12
URL      : https://github.com/lxqt/lxqt-config/releases/download/1.0.0/lxqt-config-1.0.0.tar.xz
Source0  : https://github.com/lxqt/lxqt-config/releases/download/1.0.0/lxqt-config-1.0.0.tar.xz
Source1  : https://github.com/lxqt/lxqt-config/releases/download/1.0.0/lxqt-config-1.0.0.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules pkgconfig(xcb) xcb-util-cursor-dev xcb-util-image-dev xcb-util-keysyms-dev xcb-util-renderutil-dev xcb-util-wm-dev xcb-util-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libkscreen-dev
BuildRequires : liblxqt-dev
BuildRequires : lxqt-build-tools
BuildRequires : pkg-config
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xorg-libinput)
BuildRequires : qtbase-dev
BuildRequires : qtsvg-dev
BuildRequires : qttools-dev
BuildRequires : qtx11extras-dev
BuildRequires : zlib-dev

%description
# lxqt-config
## Overview
This repository is providing several tools involved in the configuration of both
LXQt and the underlying operating system.

%prep
%setup -q -n lxqt-config-1.0.0
cd %{_builddir}/lxqt-config-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636132326
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1636132326
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lxqt-config
cp %{_builddir}/lxqt-config-1.0.0/LICENSE %{buildroot}/usr/share/package-licenses/lxqt-config/7fab4cd4eb7f499d60fe183607f046484acd6e2d
cp %{_builddir}/lxqt-config-1.0.0/lxqt-config-monitor/LICENSE %{buildroot}/usr/share/package-licenses/lxqt-config/f0aaeb9183bca4511d21c13a39052e24f3774645
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
